### ISSUE TITLE
Hex editor crash: Negative size array

### ISSUE THREAD

**Issue by bbgott** [Matrix89/ComplexLogic#22]
If you open the hex editor and click the delete byte button 3 times the game crashes with the following exception:

java.lang.NegativeArraySizeException
	at me.matrix89.complexlogic.gui.HexEditorComponent.insertByte(HexEditorComponent.java:166)
	at me.matrix89.complexlogic.gui.HexEditorGUI.func_146284_a(HexEditorGUI.java:190)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at me.matrix89.complexlogic.gui.HexEditorGUI.func_73864_a(HexEditorGUI.java:159)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at me.matrix89.complexlogic.gui.HexEditorGUI.func_146274_d(HexEditorGUI.java:108)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Matrix89** [comment]
I know about this, the current implementation of HexEditor underlying data structure is a mess. I have to rewrite it.
